version: "3"
services:

  test-base:
    image: prismagraphql/build:test
    environment:
      SERVER_ROOT: /root/build
      COMMIT_SHA: "ci_test_binary"
      RUST_BACKTRACE: "1"
      IS_BUILDKITE: "1"
      RUST_LOG_FORMAT: "devel"
      LOG_LEVEL: "error"
    volumes:
      - .:/root/build
    working_dir: /root/build/
    networks:
      - engine-tests
      
  test-db-postgres-9:
    image: postgres:9
    restart: always
    command: postgres -c 'max_connections=1000'
    environment:
      POSTGRES_PASSWORD: "prisma"
    ports:
      - "5431:5432"
    networks:
      - engine-tests

networks:
  engine-tests:
