name: Test
on:
  push:

jobs:

  test:
    name: "Test"

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Start databases"
        run: docker-compose -f docker-compose.yml up -d 

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          sudo: false

